-- AlterTable
ALTER TABLE "daily_sales_staff_cash"
ADD COLUMN     "bill_500" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "bill_200" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "bill_100" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "bill_50" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "bill_20" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "coins" DOUBLE PRECISION NOT NULL DEFAULT 0;

